version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081

  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
