# Generated by Django 2.2.3 on 2019-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lysimeter', models.CharField(max_length=10)),
                ('environment_temperature', models.CharField(max_length=10)),
                ('ambient_humidity', models.CharField(max_length=10)),
                ('ambient_light', models.CharField(max_length=10)),
                ('ground_temperature01', models.CharField(max_length=10)),
                ('ground_temperature02', models.CharField(max_length=10)),
                ('ground_temperature03', models.CharField(max_length=10)),
                ('soil_humidity01', models.CharField(max_length=10)),
                ('soil_humidity02', models.CharField(max_length=10)),
                ('soil_humidity03', models.CharField(max_length=10)),
                ('lysimeter_weight', models.CharField(max_length=10)),
                ('waste_weight', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensores',
                'order_with_respect_to': 'id_lysimeter',
            },
        ),
    ]
