# Generated by Django 2.2.3 on 2019-08-13 20:25

from django.db import migrations, models
import djongo.models.fields
import lysimeter.models


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ambient_reading', djongo.models.fields.EmbeddedModelField(model_container=lysimeter.models.AmbientReading, null=True)),
                ('device_params', djongo.models.fields.EmbeddedModelField(model_container=lysimeter.models.DeviceParams, null=True)),
                ('soil_readings', djongo.models.fields.ArrayModelField(model_container=lysimeter.models.SoilReadings)),
                ('weight', djongo.models.fields.EmbeddedModelField(model_container=lysimeter.models.Weight, null=True)),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensores',
            },
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
