# Generated by Django 2.2.3 on 2020-02-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.AlterModelOptions(
            name='deviceparams',
            options={'verbose_name': 'Lysimeter', 'verbose_name_plural': 'Lysimeters'},
        ),
        migrations.RenameField(
            model_name='deviceparams',
            old_name='ambient_light',
            new_name='ambient_light01',
        ),
        migrations.AddField(
            model_name='deviceparams',
            name='ambient_light02',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
