# Generated by Django 2.2.3 on 2020-02-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0002_auto_20190813_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Lysimeter', 'verbose_name_plural': 'Lysimeters'},
        ),
    ]
