# Generated by Django 2.2.3 on 2020-04-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0002_auto_20200209_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceparams',
            options={'ordering': ('-id',), 'verbose_name': 'Lysimeter', 'verbose_name_plural': 'Lysimeters'},
        ),
    ]
