# Generated by Django 2.2.3 on 2020-04-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0006_auto_20200410_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparams',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
