# Generated by Django 2.2.3 on 2020-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0007_auto_20200410_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparams',
            name='date_time',
            field=models.DateTimeField(verbose_name='2020-04-10 19:47:37'),
        ),
    ]
