# Generated by Django 2.2.3 on 2020-04-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0008_auto_20200410_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparams',
            name='date_time',
            field=models.CharField(default='2020-04-10 20:17:16', max_length=10),
        ),
    ]
