# Generated by Django 2.2.3 on 2020-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysimeter', '0010_auto_20200410_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparams',
            name='date_time',
            field=models.CharField(default='2020-04-10 21:35:24', max_length=20),
        ),
    ]
